version: '3'

services:

  db:
    image: mysql:8.0.25
    restart: always
    container_name: "mysql8"
    environment:
      MYSQL_ROOT_PASSWORD: 123456
    ports:
      - "3306:3306"
    volumes: 
      - ./data:/var/lib/mysql
