version: '3'

services: 
  redis:
    image: redis
    container_name: "redis"
    restart: always
    ports:
      - "6379:6379"
    volumes: 
      - ./data:/data
    networks:
      - "redisnet"
    command:
      --requirepass "he*a5792aD!2" #这一行是设置密码

networks: 
  redisnet: 
    driver: bridge